# Unimportant users
avahi = { by = "owner", priority = 20 }

# Important users
gdm = { by = "owner", priority = -10 }

# Desktop applications
"^(atom|code|firefox|mpv|chromium|chrome|joplin|cherrytree)" = { priority = -5 }

# Pentesting
"^(perl|gobuster|nmap|wkhtmltoimage|rustbuster|smbmap)" = { priority = -15, policy = "deadline" }
"^(hashcat)" = { priority = -15 }

# Desktop-critical services
"^(gdm|gnome-shell|Xorg)" = { priority = -10 }
sway = { priority = -10 }

# Compiler tasks
"^(make|cargo|rustc|rls|cicc|gcc|git)" = { priority = 20, policy = "idle" }

# Non-critical background services
"^(tracker|system76-|io.elementary.appcenter)" = { priority = 20, policy = "idle" }
"^(swaybg|swayidle)" = { priority = 20, policy = "idle" }

# Realtime services
pulseaudio = { priority = -15, policy = "deadline" }
